### PR TITLE
Fix wget_update to handle queries in URLs

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also prevent firewall caching from providing stale data (for jenkins).

### CODE REVIEW

**Comment by chrisvire** [comment]
BuildUpdate uses either curl or wget.  So, if there is a problem with caching, then it should be fixed for both curl and wget.  It looks like the correct way to add the no-cache to curl:

-H "Pragma: no-cache" -H "Cache-Control: no-cache"

**Comment by StephenMcConnel** [comment]
Okay, I've added that to the curl invocations.

**Comment by chrisvire** [comment]
I tried applying your change and then recreating bloom's build/getDependencies-Linux.sh.  Got these errors:

$ ../BuildUpdate/buildupdate.rb -f build/getDependencies-Linux.sh 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /home/hubbard/src/BuildUpdate/script_actions.rb:62: syntax error, unexpected tCONSTANT, expecting keyword_end (SyntaxError)
    "curl -# -L -H "Pragma: no-cache" -H "Cache-Control...
                          ^
/home/hubbard/src/BuildUpdate/script_actions.rb:62: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...url -# -L -H "Pragma: no-cache" -H "Cache-Control: no-cache"...
...                               ^
/home/hubbard/src/BuildUpdate/script_actions.rb:62: syntax error, unexpected tCONSTANT, expecting keyword_end
...-H "Pragma: no-cache" -H "Cache-Control: no-cache" -z #{dst}...
...                               ^
/home/hubbard/src/BuildUpdate/script_actions.rb:62: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...e" -H "Cache-Control: no-cache" -z #{dst} -o #{dst} #{src}"
...                               ^
/home/hubbard/src/BuildUpdate/script_actions.rb:66: syntax error, unexpected tCONSTANT, expecting keyword_end
    "curl -# -L -H "Pragma: no-cache" -H "Cache-Control...
                          ^
/home/hubbard/src/BuildUpdate/script_actions.rb:66: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...url -# -L -H "Pragma: no-cache" -H "Cache-Control: no-cache"...
...                               ^
/home/hubbard/src/BuildUpdate/script_actions.rb:66: syntax error, unexpected tCONSTANT, expecting keyword_end
...-H "Pragma: no-cache" -H "Cache-Control: no-cache" -o #{dst}...
...                               ^
/home/hubbard/src/BuildUpdate/script_actions.rb:66: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...e" -H "Cache-Control: no-cache" -o #{dst} #{src}"
...                               ^
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from ../BuildUpdate/buildupdate.rb:15:in `<main>'

**Comment by chrisvire** [comment]
It should be:

  def curl_update(src, dst)
    %Q[curl -# -L -H "Pragma: no-cache" -H "Cache-Control: no-cache" -z #{dst} -o #{dst} #{src}]
  end

  def curl_replace(src, dst)
    %Q[curl -# -L -H "Pragma: no-cache" -H "Cache-Control: no-cache" -o #{dst} #{src}]
  end

**Pull request closed without merging**
